import 'dart:convert';
import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:uuid/uuid.dart';

void main() => runApp(const LockedInApp());

const emerald = Color(0xFF10B981);
const gold = Color(0xFFD4AF37);
const bg = Color(0xFF101615);
const card = Color(0xFF171D1B);

class Store extends ChangeNotifier {
  static const _key = 'locked_in_v4_state';
  Map<String, dynamic> state = {
    'profile': {}, 'workouts': [], 'habits': [], 'study': [], 'water': 0,
    'xp': 0, 'streak': 0, 'lastDay': '', 'quests': {}, 'settings': {'incognito': false}
  };
  bool ready = false;
  Future<void> load() async {
    final p = await SharedPreferences.getInstance();
    final raw = p.getString(_key);
    if (raw != null) state = Map<String,dynamic>.from(jsonDecode(raw));
    ready = true; notifyListeners();
  }
  Future<void> save() async {
    final p = await SharedPreferences.getInstance();
    await p.setString(_key, jsonEncode(state)); notifyListeners();
  }
  bool get onboarded => (state['profile'] as Map).isNotEmpty;
  int get xp => state['xp'] as int? ?? 0;
  int get level => (xp ~/ 500) + 1;
  String get rank { final l=level; if(l>=20)return 'TITAN'; if(l>=10)return 'STEEL'; if(l>=5)return 'IRON'; return 'ROOKIE'; }
  Future<void> award(int amount) async { state['xp']=(xp+amount); await save(); }
  Future<void> addWorkout(Map<String,dynamic> w) async { (state['workouts'] as List).add(w); await award(25); await refreshStreak(); }
  Future<void> addStudy(int minutes, String subject) async { (state['study'] as List).add({'id':const Uuid().v4(),'minutes':minutes,'subject':subject,'at':DateTime.now().toIso8601String()}); await award((minutes/5).round().clamp(5,100)); await refreshStreak(); }
  Future<void> toggleHabit(String id) async { final h=(state['habits'] as List).firstWhere((x)=>x['id']==id); h['done']=!(h['done']??false); if(h['done']==true) await award(10); await refreshStreak(); }
  Future<void> refreshStreak() async { final today=DateTime.now().toIso8601String().substring(0,10); if(state['lastDay']!=today){ state['streak']=(state['streak'] as int? ?? 0)+1; state['lastDay']=today; await save(); } }
  Future<void> setWater(int ml) async { state['water']=ml; await save(); }
}

class LockedInApp extends StatefulWidget { const LockedInApp({super.key}); @override State<LockedInApp> createState()=>_LockedInAppState(); }
class _LockedInAppState extends State<LockedInApp> {
  final store=Store();
  @override void initState(){super.initState(); store.load();}
  @override Widget build(BuildContext c)=>AnimatedBuilder(animation:store,builder:(_,__)=>MaterialApp(debugShowCheckedModeBanner:false,theme:ThemeData(brightness:Brightness.dark,scaffoldBackgroundColor:bg,colorScheme:ColorScheme.fromSeed(seedColor:emerald,brightness:Brightness.dark),fontFamily:'Arial'),home:!store.ready?const Scaffold(body:Center(child:CircularProgressIndicator())):store.onboarded?Shell(store:store):Onboarding(store:store)));
}

class Onboarding extends StatefulWidget { final Store store; const Onboarding({super.key,required this.store}); @override State<Onboarding> createState()=>_OnboardingState(); }
class _OnboardingState extends State<Onboarding>{ final name=TextEditingController(); final age=TextEditingController(); final height=TextEditingController(); final weight=TextEditingController(); String type='HYBRID'; String diet='Vegetarian';
 Widget field(String label,TextEditingController c,{bool number=false})=>TextField(controller:c,keyboardType:number?TextInputType.number:null,decoration:InputDecoration(labelText:label));
 @override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Center(child:SingleChildScrollView(padding:const EdgeInsets.all(24),child:ConstrainedBox(constraints:const BoxConstraints(maxWidth:600),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('LOCKED IN',style:TextStyle(fontSize:38,fontWeight:FontWeight.w900,letterSpacing:2)),const SizedBox(height:4),const Text('YOUR PERSONAL OPERATING SYSTEM',style:TextStyle(color:emerald,fontWeight:FontWeight.bold)),const SizedBox(height:30),field('Name',name),field('Age',age,number:true),field('Height (cm)',height,number:true),field('Weight (kg)',weight,number:true),const SizedBox(height:18),const Text('GOAL PHYSIQUE',style:TextStyle(fontWeight:FontWeight.bold)),Wrap(spacing:8,children:['SLEEPER','BULK','HYBRID'].map((x)=>ChoiceChip(label:Text(x),selected:type==x,onSelected:(_)=>setState(()=>type=x))).toList()),const SizedBox(height:18),const Text('DIET',style:TextStyle(fontWeight:FontWeight.bold)),DropdownButton<String>(value:diet,isExpanded:true,items:['Vegetarian','Vegan','Non-vegetarian','Pescatarian','Custom'].map((x)=>DropdownMenuItem(value:x,child:Text(x))).toList(),onChanged:(x)=>setState(()=>diet=x!)),const SizedBox(height:22),const Text('Everything is stored locally in this client until you connect your own server.',style:TextStyle(color:Colors.white54)),const SizedBox(height:24),SizedBox(width:double.infinity,child:FilledButton(onPressed:(){widget.store.state['profile']={'name':name.text.trim(),'age':int.tryParse(age.text),'height':double.tryParse(height.text),'weight':double.tryParse(weight.text),'bodyType':type,'diet':diet,'createdAt':DateTime.now().toIso8601String()}; widget.store.state['habits']=[{'id':'water','name':'Hydration','done':false},{'id':'study','name':'Study','done':false},{'id':'hygiene','name':'Hygiene','done':false},{'id':'mobility','name':'Mobility','done':false}]; widget.store.save();},child:const Padding(padding:EdgeInsets.all(14),child:Text('ENTER THE GRIND →',style:TextStyle(fontWeight:FontWeight.w900))))])))))); }
}

class Shell extends StatefulWidget { final Store store; const Shell({super.key,required this.store}); @override State<Shell> createState()=>_ShellState(); }
class _ShellState extends State<Shell>{ int tab=0; final pages=['Home','Train','Mind','Life','Squad']; @override Widget build(BuildContext c){ final views=[Home(store:widget.store),Train(store:widget.store),Mind(store:widget.store),Life(store:widget.store),Squad(store:widget.store)]; return Scaffold(body:SafeArea(child:views[tab]),bottomNavigationBar:NavigationBar(selectedIndex:tab,onDestinationSelected:(i)=>setState(()=>tab=i),destinations:const [NavigationDestination(icon:Icon(Icons.home_outlined),selectedIcon:Icon(Icons.home),label:'Home'),NavigationDestination(icon:Icon(Icons.fitness_center_outlined),selectedIcon:Icon(Icons.fitness_center),label:'Train'),NavigationDestination(icon:Icon(Icons.psychology_outlined),selectedIcon:Icon(Icons.psychology),label:'Mind'),NavigationDestination(icon:Icon(Icons.auto_awesome_outlined),selectedIcon:Icon(Icons.auto_awesome),label:'Life'),NavigationDestination(icon:Icon(Icons.groups_outlined),selectedIcon:Icon(Icons.groups),label:'Squad')])); }}

class Page extends StatelessWidget { final String title; final Widget child; const Page({super.key,required this.title,required this.child}); @override Widget build(BuildContext c)=>CustomScrollView(slivers:[SliverPadding(padding:const EdgeInsets.fromLTRB(18,18,18,100),sliver:SliverList(delegate:SliverChildListDelegate([Text(title,style:const TextStyle(fontSize:34,fontWeight:FontWeight.w900)),const SizedBox(height:5),child])))]); }
Widget stat(String a,String b,{Color color=emerald})=>Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:card,borderRadius:BorderRadius.circular(18)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:TextStyle(fontSize:30,fontWeight:FontWeight.w900,color:color)),Text(b,style:const TextStyle(color:Colors.white54))]));

class Home extends StatelessWidget{final Store store;const Home({super.key,required this.store});@override Widget build(BuildContext c){final p=store.state['profile'] as Map;final ws=store.state['workouts'] as List;final st=store.state['streak'];return Page(title:'LOCK IN, ${p['name']??'ATHLETE'}',child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Wrap(spacing:10,runSpacing:10,children:[stat('$st 🔥','DAY STREAK'),stat('${store.xp}','XP'),stat('LVL ${store.level}','${store.rank}'),stat('${ws.length}','WORKOUTS')]),const SizedBox(height:18),const Text("TODAY'S LOCK-IN",style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:10),Card(color:card,child:Padding(padding:const EdgeInsets.all(18),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('TRAIN • STUDY • RECOVER',style:TextStyle(fontSize:20,fontWeight:FontWeight.bold)),const SizedBox(height:8),Text('Goal mode: ${p['bodyType']??'HYBRID'}  •  ${p['diet']??'Custom'}',style:const TextStyle(color:Colors.white60)),const SizedBox(height:14),LinearProgressIndicator(value:((store.xp%500)/500).clamp(0,1),minHeight:8)]))),const SizedBox(height:18),const Text('QUICK ACTIONS',style:TextStyle(fontSize:18,fontWeight:FontWeight.w900)),const SizedBox(height:10),Wrap(spacing:8,children:[ActionChip(label:const Text('＋ Workout'),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>LogWorkout(store:store)))),ActionChip(label:const Text('💧 Water'),onPressed:()=>showDialog(context:c,builder:(_)=>WaterDialog(store:store))),ActionChip(label:const Text('⏱ Study'),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>StudyTimer(store:store))))]) ]));}}

class Train extends StatelessWidget{final Store store;const Train({super.key,required this.store});@override Widget build(BuildContext c){final ws=List<Map<String,dynamic>>.from(store.state['workouts'].map((x)=>Map<String,dynamic>.from(x)));return Page(title:'TRAIN',child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[FilledButton.icon(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>LogWorkout(store:store))),icon:const Icon(Icons.add),label:const Text('LOG SESSION')),const SizedBox(height:18),if(ws.isEmpty)const Empty('No workouts logged yet. Your first session starts the history.') else ...ws.reversed.take(20).map((w)=>Card(color:card,child:ListTile(title:Text(w['name']),subtitle:Text('${w['sets']} sets • ${w['reps']} reps • ${w['weight']} kg'),trailing:Text('+25 XP',style:const TextStyle(color:emerald,fontWeight:FontWeight.bold))))]));}}
class LogWorkout extends StatefulWidget{final Store store;const LogWorkout({super.key,required this.store});@override State<LogWorkout> createState()=>_LogWorkoutState();}
class _LogWorkoutState extends State<LogWorkout>{final ex=TextEditingController();final sets=TextEditingController(text:'3');final reps=TextEditingController(text:'10');final weight=TextEditingController(text:'0');@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('LOG WORKOUT')),body:Padding(padding:const EdgeInsets.all(20),child:Column(children:[TextField(controller:ex,decoration:const InputDecoration(labelText:'Exercise / activity')),TextField(controller:sets,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Sets')),TextField(controller:reps,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Reps / duration')),TextField(controller:weight,keyboardType:TextInputType.number,decoration:const InputDecoration(labelText:'Weight (kg, optional)')),const Spacer(),SizedBox(width:double.infinity,child:FilledButton(onPressed:()async{await widget.store.addWorkout({'id':const Uuid().v4(),'name':ex.text.isEmpty?'Custom session':ex.text,'sets':int.tryParse(sets.text)??0,'reps':int.tryParse(reps.text)??0,'weight':double.tryParse(weight.text)??0,'at':DateTime.now().toIso8601String()});if(mounted)Navigator.pop(c);},child:const Text('SAVE • +25 XP')))])));}

class Mind extends StatelessWidget{final Store store;const Mind({super.key,required this.store});@override Widget build(BuildContext c){final s=store.state['study'] as List;return Page(title:'MIND',child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Card(color:card,child:ListTile(leading:const Icon(Icons.timer,color:emerald),title:const Text('STUDY LOCK-IN'),subtitle:const Text('Pomodoro + real study history'),trailing:FilledButton(onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>StudyTimer(store:store))),child:const Text('START')))),const SizedBox(height:15),Text('TOTAL STUDY: ${s.fold<int>(0,(a,x)=>a+(x['minutes'] as int))} MIN',style:const TextStyle(fontWeight:FontWeight.bold)),const SizedBox(height:10),if(s.isEmpty)const Empty('No study sessions yet.') else ...s.reversed.take(20).map((x)=>ListTile(title:Text(x['subject']),trailing:Text('${x['minutes']}m')))]));}}
class StudyTimer extends StatefulWidget{final Store store;const StudyTimer({super.key,required this.store});@override State<StudyTimer> createState()=>_StudyTimerState();}
class _StudyTimerState extends State<StudyTimer>{int seconds=1500;bool running=false;String subject='General study';@override void initState(){super.initState();_tick();}void _tick()async{while(mounted){await Future.delayed(const Duration(seconds:1));if(running&&seconds>0)setState(()=>seconds--);}}@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('STUDY LOCK-IN')),body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[Text('${seconds~/60}:${(seconds%60).toString().padLeft(2,'0')}',style:const TextStyle(fontSize:76,fontWeight:FontWeight.w900)),TextField(decoration:const InputDecoration(labelText:'Subject'),onChanged:(v)=>subject=v),const SizedBox(height:20),FilledButton(onPressed:()=>setState(()=>running=!running),child:Text(running?'PAUSE':'START')),TextButton(onPressed:()async{final m=((1500-seconds)/60).floor();if(m>0)await widget.store.addStudy(m,subject);if(mounted)Navigator.pop(c);},child:const Text('SAVE SESSION'))]))));}

class Life extends StatefulWidget{final Store store;const Life({super.key,required this.store});@override State<Life> createState()=>_LifeState();}
class _LifeState extends State<Life>{@override Widget build(BuildContext c){final hs=List<Map<String,dynamic>>.from(widget.store.state['habits'].map((x)=>Map<String,dynamic>.from(x)));return Page(title:'LIFE',child:Column(children:[...hs.map((h)=>Card(color:card,child:CheckboxListTile(value:h['done']==true,onChanged:(_){widget.store.toggleHabit(h['id']);},title:Text(h['name']),secondary:const Icon(Icons.check_circle_outline))),),const SizedBox(height:12),const Card(color:card,child:Padding(padding:EdgeInsets.all(16),child:Text('Build consistency: training, study, hygiene, mobility and recovery all contribute to your lock-in score.')))]));}}
class Squad extends StatelessWidget{final Store store;const Squad({super.key,required this.store});@override Widget build(BuildContext c)=>Page(title:'SQUAD',child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[const Card(color:card,child:ListTile(leading:Icon(Icons.lock,color:gold),title:Text('PRIVATE SQUAD'),subtitle:Text('Invite-only. Connect this client to your self-hosted server for real friends and leaderboards.'))),const SizedBox(height:12),stat('${store.xp}','YOUR XP'),const SizedBox(height:12),const Empty('No squad members are synced yet.') ]));}

class WaterDialog extends StatefulWidget{final Store store;const WaterDialog({super.key,required this.store});@override State<WaterDialog> createState()=>_WaterDialogState();}
class _WaterDialogState extends State<WaterDialog>{int ml=0;@override Widget build(BuildContext c)=>AlertDialog(title:const Text('HYDRATION'),content:Column(mainAxisSize:MainAxisSize.min,children:[Text('${ml} ml',style:const TextStyle(fontSize:36,fontWeight:FontWeight.w900)),Wrap(spacing:6,children:[100,250,500].map((x)=>ActionChip(label:Text('+$x'),onPressed:()=>setState(()=>ml+=x))).toList())]),actions:[TextButton(onPressed:(){widget.store.setWater((widget.store.state['water'] as int)+ml);Navigator.pop(c);},child:const Text('SAVE'))]);}}
class Empty extends StatelessWidget{final String text;const Empty(this.text,{super.key});@override Widget build(BuildContext c)=>Container(width:double.infinity,padding:const EdgeInsets.all(24),decoration:BoxDecoration(color:card,borderRadius:BorderRadius.circular(18)),child:Text(text,style:const TextStyle(color:Colors.white54)));}
