(function(){"use strict";
function app(){return window.app;}
function data(){return app().state();}
function field(label,name,type){return "<label>"+label+"<input name=\""+name+"\" type=\""+type+"\" required></label>";}
function vaultMarkup(items){var list=items.length?items.map(function(item){return "<div class=\"activity-row\"><strong>"+app().escape(item.title)+"</strong><small>"+app().escape(item.detail)+"</small></div>";}).join(""):"<p class=\"empty\">Your vault is empty. Add one idea worth returning to.</p>";return "<div class=\"activity-list\">"+list+"</div>";}
function drillMarkup(items){var source=window.LOCKED_DATA&&window.LOCKED_DATA.skillProgressions?window.LOCKED_DATA.skillProgressions:new Array();var list=source.map(function(item){return "<article class=\"goal\"><strong>"+app().escape(item.skill)+"</strong><small>"+app().escape(item.frequency)+" · "+app().escape(item.benchmark)+"</small><p>"+app().escape(item.steps.join(" → "))+"</p><button class=\"btn primary\" data-action=\"startDrill\" data-skill=\""+app().escape(item.skill)+"\">Start drill</button></article>;}).join("");var recent=items.length?"<p class=\"muted\">Last drill: "+app().escape(items[0].skill)+" · "+app().escape(items[0].summary)+"</p>":"<p class=\"muted\">No drills recorded yet.</p>";return recent+"<div class=\"goal-list\">"+list+"</div>";}
function depthView(){var state=data();return hero("DEEP WORK","Vault and skill lab","Keep the ideas and drills that compound your next level.")+card("Vault",vaultMarkup(state.vault))+"<section class=\"card\"><h2>Add to vault</h2><form id=\"vault-form\" class=\"inline-form\"><label>Title<input name=\"title\" required></label><label>Search or detail<input name=\"detail\" required></label><button class=\"btn primary\">Save note</button></form></section>"+card("Skill drill library",drillMarkup(state.drills))+"<section class=\"card\"><h2>Unprompted speaking drill</h2><form id=\"speaking-form\" class=\"form-grid\">"+field("Topic","topic","text")+field("Timer minutes","minutes","number")+"<button class=\"btn primary\">Start speaking drill</button></form><div id=\"drill-session\"></div></section>";}
function hero(kicker,title,text){return "<div class=\"hero\"><div class=\"eyebrow\">"+app().escape(kicker)+"</div><h1>"+app().escape(title)+"</h1><p class=\"muted\">"+app().escape(text)+"</p></div>;}
function card(title,body){return "<section class=\"card\"><h2>"+app().escape(title)+"</h2>"+body+"</section>;}
function saveVault(form){var state=data();state.vault.unshift({id:Date.now(),title:form.title.value.trim(),detail:form.detail.value.trim(),date:new Date().toISOString()});state.vault=state.vault.slice(0,50);app().save();app().render();app().toast("Vault note saved");}
function startDrill(node){var skill=node.getAttribute("data-skill");var state=data();state.drills.unshift({skill:skill,summary:"Started skill drill",date:new Date().toISOString()});app().save();app().toast(skill+" drill started");app().render();}
function startSpeaking(form){var topic=form.topic.value.trim();var minutes=Math.max(1,Number(form.minutes.value)||2);var node=document.getElementById("drill-session");if(!node)return;var end=Date.now()+minutes*60000;node.innerHTML="<div class=\"cinematic-card\"><strong>Speak now: "+app().escape(topic)+"</strong><p id=\"drill-clock\">"+minutes+":00 remaining</p><button class=\"btn\" data-action=\"recordSpeaking\" data-topic=\""+app().escape(topic)+"\">Record summary</button></div>";window.clearInterval(window.LI speakingTimer);window.LI speakingTimer=window.setInterval(function(){var left=Math.max(0,end-Date.now());var clock=document.getElementById("drill-clock");if(clock)clock.textContent=Math.floor(left/60000)+":"+String(Math.floor(left/1000)%60).padStart(2,"0")+" remaining";if(!left)window.clearInterval(window.LI speakingTimer);},1000);}
function recordSpeaking(node){var summary=window.prompt("What did you say and what will you improve?","Clear opening, three points, strong close");if(summary===null)return;var state=data();state.drills.unshift({skill:"Unprompted speaking",summary:summary,topic:node.getAttribute("data-topic"),date:new Date().toISOString()});app().save();app().render();app().toast("Speaking drill summarized");}
function bind(){if(!app())return;app().registerView("depth",depthView);app().registerView("advanced",depthView);app().registerAction("startDrill",startDrill);app().registerAction("recordSpeaking",recordSpeaking);document.addEventListener("submit",function(event){if(event.target.id==="vault-form"){event.preventDefault();saveVault(event.target);}if(event.target.id==="speaking-form"){event.preventDefault();startSpeaking(event.target);}});}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind,{once:true});else bind();
}());
