(function(){'use strict';
function getApp(){return window.app||window.LockedIn;}
function levelData(app){var xp=app.num(app.state().xp,0);var level=Math.floor(xp/100)+1;var progress=xp%100;return {xp:xp,level:level,progress:progress};}
function addStyle(){if(document.getElementById('level-style'))return;var style=document.createElement('style');style.id='level-style';style.textContent='.levelBadge{display:inline-flex;align-items:center;gap:6px;border:1px solid rgba(156,255,87,.35);border-radius:20px;background:rgba(156,255,87,.08);color:#9cff57;padding:7px 11px;font-size:12px;font-weight:800}.levelPanel{margin:16px 0;border:1px solid rgba(156,255,87,.3);border-radius:18px;background:linear-gradient(135deg,rgba(156,255,87,.13),rgba(23,31,45,.96));padding:18px}.levelPanel strong{color:#9cff57}.levelBar{height:9px;border-radius:20px;background:#273244;overflow:hidden;margin-top:11px}.levelBar span{display:block;height:100%;border-radius:20px;background:linear-gradient(90deg,#62d83a,#b7ff78)}.levelBanner{animation:levelPulse 2.2s ease-in-out infinite}.levelFeed{border-color:rgba(156,255,87,.28)}@keyframes levelPulse{0%,100%{box-shadow:0 0 0 rgba(156,255,87,0)}50%{box-shadow:0 0 24px rgba(156,255,87,.28)}}';document.head.appendChild(style);}
function makeNode(tag,text){var item=document.createElement(tag);if(text!==undefined)item.textContent=text;return item;}
function decorate(){var app=getApp();if(!app||location.hash!=='#dashboard')return;addStyle();var data=levelData(app);var root=document.getElementById('app');if(!root)return;var old=root.querySelector('.levelPanel');if(old)old.remove();var panel=document.createElement('section');panel.className='levelPanel levelBanner';panel.setAttribute('data-level-panel','true');var heading=makeNode('div');heading.appendChild(makeNode('small','LEVEL PROGRESS'));var title=makeNode('h2','Level ');title.appendChild(makeNode('strong',data.level));heading.appendChild(title);var summary=makeNode('p');summary.className='muted';summary.appendChild(document.createTextNode(data.xp+' XP total '+(100-data.progress)+' XP to level '+(data.level+1)));heading.appendChild(summary);panel.appendChild(heading);var bar=document.createElement('div');bar.className='levelBar';bar.setAttribute('aria-label','XP progress');var fill=document.createElement('span');fill.style.width=data.progress+'%';bar.appendChild(fill);panel.appendChild(bar);panel.appendChild(makeNode('small',data.progress+' / 100 XP'));var hero=root.querySelector('.hero');if(hero&&hero.parentNode)hero.parentNode.insertBefore(panel,hero.nextSibling);var list=root.querySelector('.activity-list');if(list&&!list.querySelector('.levelFeed')){var feed=document.createElement('div');feed.className='activity-row levelFeed';feed.appendChild(makeNode('strong','Level '+data.level+' progress'));feed.appendChild(makeNode('small',data.progress+'% toward the next level'));list.insertBefore(feed,list.firstChild);}}
function install(){var app=getApp();if(!app||app.levelReady)return;app.levelReady=true;var render=app.render;app.render=function(){render();setTimeout(decorate,0);};window.addEventListener('hashchange',function(){setTimeout(decorate,0);});setTimeout(decorate,0);}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',install,{once:true});else install();
}());
