(function () {
  'use strict';
  var D = window.LOCKED_DATA || { exercises: [['Back Squat','Quads'],['Bench Press','Chest'],['Pull Up','Back'],['Deadlift','Posterior'],['Plank','Core']], meals: [['Protein oats',520,38,58,16],['Chicken rice bowl',680,52,74,18]], subjects: ['Math','Biology','History'], habits: ['Train or walk','2L water','Read 20 minutes','Morning skincare','No phone in bed'], skills: ['Muscle-up','Front lever','Public speaking'] };
  var K = 'locked-in-v3-state';
  var base = { profile:{name:'Operator',goals:'strength, confidence, consistency'}, route:'dashboard', xp:420, streak:7, logs:[], meals:[], study:[], journal:[], mood:[], habits:{}, water:4, quests:{}, badges:['FIRST LOCK-IN'], onboarded:false };
  function clone(x){ try{return JSON.parse(JSON.stringify(x));}catch(e){return x;} }
  function load(){ var s=clone(base), raw=null; try{raw=localStorage.getItem(K);}catch(e){} if(raw){try{s=Object.assign(s,JSON.parse(raw));}catch(e2){}} s.profile=Object.assign(clone(base.profile),s.profile||{}); ['logs','meals','study','journal','mood','badges'].forEach(function(k){if(!Array.isArray(s[k]))s[k]=[];}); if(!s.habits||typeof s.habits!=='object'||Array.isArray(s.habits))s.habits={}; if(!s.quests||typeof s.quests!=='object'||Array.isArray(s.quests))s.quests={}; s.xp=Number.isFinite(+s.xp)?+s.xp:base.xp; s.streak=Number.isFinite(+s.streak)?+s.streak:base.streak; s.water=Number.isFinite(+s.water)?+s.water:base.water; return s; }
  var S=load(), interval=null;
  function $(q){return document.querySelector(q);} function day(){return new Date().toISOString().slice(0,10);} function gap(a,b){var x=new Date(a+'T00:00:00'),y=new Date(b+'T00:00:00');return isNaN(x)||isNaN(y)?Infinity:Math.round((y-x)/86400000);} function esc(x){return String(x==null?'':x).replace(/[&<>"']/g,function(c){return ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'})[c];});}
  function save(){try{localStorage.setItem(K,JSON.stringify(S));}catch(e){} var x=$('#save-status');if(x)x.textContent='SAVED LOCALLY';}
  function toast(m){var x=$('#toast');if(!x)return;x.textContent=m;x.classList.add('show');setTimeout(function(){x.classList.remove('show');},1800);}
  function currency(){var n=Number(S.creatine);if(!Number.isFinite(n))n=S.currencies&&Number(S.currencies.CREATINE);if(!Number.isFinite(n))n=S.currency&&Number(S.currency.CREATINE);S.creatine=Math.max(0,Number.isFinite(n)?n:0);S.currencies=Object.assign({},S.currencies||{},{CREATINE:S.creatine});S.currency=Object.assign({},S.currency||{},{CREATINE:S.creatine});}
  function addCreatine(n){currency();S.creatine+=Math.max(0,Number(n)||0);S.currencies.CREATINE=S.creatine;S.currency.CREATINE=S.creatine;return S.creatine;}
  var defs=[{id:'workout',title:'Log one training session',target:1,xp:50},{id:'water',title:'Hit 8 glasses of water',target:8,xp:50},{id:'study',title:'Complete 25 minutes of focus',target:25,xp:50}];
  function resetQuests(){S.quests={};defs.forEach(function(q){S.quests[q.id]={id:q.id,title:q.title,target:q.target,progress:0,completed:false,xp:q.xp,action:q.id,date:day();}});S.dailyQuestDate=day();}
  function quests(){if(S.dailyQuestDate!==day()||Object.keys(S.quests).length!==3)resetQuests();Object.keys(S.quests).forEach(function(k){var q=S.quests[k];if(typeof q==='boolean')S.quests[k]={id:k,title:k,target:1,progress:q?1:0,completed:q,xp:50,action:k,date:day()};else{q.progress=Math.max(0,+q.progress||0);q.target=Math.max(1,+q.target||1);q.completed=!!(q.completed||q.progress>=q.target);}});}
  function habits(){if(!S.habitMeta||typeof S.habitMeta!=='object'||Array.isArray(S.habitMeta))S.habitMeta={};if(!Array.isArray(S.streakFeed))S.streakFeed=[];(D.habits||[]).forEach(function(h){if(!S.habitMeta[h])S.habitMeta[h]={lastCheckDate:null,consecutiveDays:0};var m=S.habitMeta[h];m.consecutiveDays=Math.max(0,+m.consecutiveDays||0);if(m.lastCheckDate&&gap(m.lastCheckDate,day())>1)m.consecutiveDays=0;});}
  function resetBrokenStreaks(){habits();Object.keys(S.habitMeta).forEach(function(h){var m=S.habitMeta[h];if(m.lastCheckDate&&gap(m.lastCheckDate,day())>1&&m.consecutiveDays){m.consecutiveDays=0;S.streakFeed.unshift({type:'reset',habit:h,date:day(),consecutiveDays:0});}});S.streakFeed=S.streakFeed.slice(0,100);}
  function creatineFor(a){a=String(a||'').toLowerCase();if(a==='train'||a==='training'||a==='exercise')a='workout';if(a==='studying'||a==='focus')a='study';if(a==='pomo-complete')a='pomodoro';return ({workout:1,habit:1,water:1,fasting:2,study:1,pomodoro:2})[a]||0;}
  function questProgress(a,n,meta){if(meta&&meta.skipQuest)return;var k=String(a||'').toLowerCase();if(k==='train'||k==='training'||k==='exercise')k='workout';if(k==='studying'||k==='focus'||k==='pomodoro'||k==='pomo-complete')k='study';var q=S.quests[k];if(!q||q.completed)return;q.progress=Math.min(q.target,q.progress+Math.max(0,+n||1));if(q.progress>=q.target){q.completed=true;awardXP(q.xp,'quest-complete',{quest:q.id,skipQuest:true,skipCreatine:true});toast('Quest complete. +'+q.xp+' XP');}}
  function awardXP(n,action,meta){meta=meta||{};quests();n=Math.max(0,+n||0);S.xp+=n;var e=Object.assign({type:'action',action:String(action||'action'),xp:n,date:day(),timestamp:new Date().toISOString(),pr:false},meta);delete e.skipQuest;delete e.skipCreatine;S.logs.push(e);var c=creatineFor(action);if(c&&!meta.skipCreatine)addCreatine(c*(+meta.creatineMultiplier||1));questProgress(action,meta.questAmount==null?1:meta.questAmount,meta);save();return e;}
  function checked(h){return !!(S.habitMeta&&S.habitMeta[h]&&S.habitMeta[h].lastCheckDate===day());}
  function checkHabit(h,on){h=String(h||'').trim();if(!h)return false;habits();if(!S.habitMeta[h])S.habitMeta[h]={lastCheckDate:null,consecutiveDays:0};var m=S.habitMeta[h];if(on===false){S.habits[h]=false;save();render();return false;}if(checked(h))return true;var d=m.lastCheckDate?gap(m.lastCheckDate,day()):Infinity;m.consecutiveDays=d===1?m.consecutiveDays+1:1;m.lastCheckDate=day();S.habits[h]=true;S.streak=Math.max(1,+S.streak||0,m.consecutiveDays);S.streakFeed.unshift({type:'habit',habit:h,date:day(),consecutiveDays:m.consecutiveDays});awardXP(10,'habit',{habit:h,consecutiveDays:m.consecutiveDays});toast('Habit locked in. +10 XP');render();return true;}
  function toggleHabit(h){return checkHabit(h,!checked(h));}
  function adjustWater(n){n=Number(n);if(!Number.isFinite(n)||!n)return S.water;if(n<0){S.water=Math.max(0,S.water+Math.floor(n));save();render();return S.water;}n=Math.floor(n);S.water+=n;awardXP(2*n,'water',{glasses:n,questAmount:n});toast('Hydration logged.');render();return S.water;}
  function waterIncrement(n){return adjustWater(Math.abs(Number(n)||1));} function waterDecrement(n){return adjustWater(-Math.abs(Number(n)||1));} function logWater(n){return adjustWater(n==null?1:n);}
  function logWorkout(o){o=o||{};var ex=String(o.exercise||o.name||'').trim();if(!ex)return false;var w=Math.max(0,+o.weight||0),r=Math.max(1,+o.reps||1),sets=Math.max(1,+o.sets||1),old=S.logs.filter(function(x){return x.type==='workout'&&x.exercise===ex;}).reduce(function(a,x){return Math.max(a,+x.weight||0);},0),pr=w>old,e={type:'workout',action:'workout',exercise:ex,weight:w,reps:r,sets:sets,date:day(),timestamp:new Date().toISOString(),pr:pr};S.logs.push(e);S.xp+=pr?35:15;addCreatine(1);questProgress('workout',1,{});save();toast(pr?'Personal record. +35 XP':'Training logged. +15 XP');render();return e;}
  function logStudy(minutes,subject){minutes=Math.max(1,+minutes||25);var e={type:'study',action:'study',minutes:minutes,subject:subject||'',date:day(),timestamp:new Date().toISOString()};S.study.push(e);awardXP(Math.round(minutes*.8),'study',{minutes:minutes,subject:subject||'',questAmount:minutes});render();return e;}
  function completePomodoro(minutes,subject){minutes=Math.max(1,+minutes||25);var e={type:'pomodoro',action:'pomodoro',minutes:minutes,subject:subject||'',date:day(),timestamp:new Date().toISOString()};S.study.push(e);awardXP(20,'pomodoro',{minutes:minutes,subject:subject||'',questAmount:minutes});toast('Pomodoro complete.');render();return e;}
  function startFasting(){S.fasting=Object.assign({},S.fasting||{},{active:true,startedAt:new Date().toISOString()});save();return S.fasting;}
  function completeFasting(hours){S.fasting=Object.assign({},S.fasting||{},{active:false,lastCompletedDate:day(),totalSessions:+((S.fasting||{}).totalSessions)||0});S.fasting.totalSessions++;awardXP(25,'fasting',{hours:+hours||0});toast('Fast logged.');render();return S.fasting;}
  function stat(a,b,c){return '<div class="stat"><small>'+esc(a)+'</small><strong>'+esc(b)+'</strong><span>'+esc(c)+'</span></div>';}
  function card(t,b){return '<section class="card"><h3>'+esc(t)+'</h3>'+b+'</section>';}
  function layout(t,e,b){return '<div class="page"><div class="title"><div><small class="eyebrow">'+esc(e)+'</small><h1>'+esc(t)+'</h1></div></div>'+b+'</div>';}
  function questHtml(){quests();return Object.keys(S.quests).map(function(k){var q=S.quests[k];return '<button class="row" data-a="quest" data-q="'+esc(k)+'"><b class="check">'+(q.completed?'✓':'')+'</b><span><strong>'+esc(q.title)+'</strong><small>'+q.progress+'/'+q.target+' · +'+q.xp+' XP</small></span></button>';}).join('');}
  function dashboard(){return layout('Dashboard',"TODAY'S OPERATING SYSTEM",'<div class="stats">'+stat('STREAK',S.streak,'days locked in')+stat('XP',S.xp,'lifetime earned')+stat('TODAY',S.logs.filter(function(x){return x.date===day();}).length,'actions logged')+stat('CREATINE',S.creatine,'earned')+'</div><div class="cols">'+card('Daily quests',questHtml())+card('Streak feed',(S.streakFeed||[]).slice(0,8).map(function(x){return '<div class="row"><b>↗</b><span><strong>'+esc(x.habit||x.type)+'</strong><small>'+esc(x.date)+' · '+(x.consecutiveDays||0)+' day streak</small></span></div>';}).join('')+'</div>');}
  function train(){var ex=(D.exercises||[]).concat(S.customExercises||[]).map(function(x){return Array.isArray(x)?x[0]:x;});return layout('Train','PERFORMANCE LAB','<div class="stats">'+stat('SESSIONS',S.logs.filter(function(x){return x.type==='workout';}).length,'logged')+stat('PRS',S.logs.filter(function(x){return x.pr;}).length,'records')+'</div><div class="cols">'+card('Quick training log','<form data-f="train" class="form"><select name="exercise">'+ex.map(function(x){return '<option>'+esc(x)+'</option>';}).join('')+'</select><input name="weight" type="number" placeholder="kg"><input name="reps" type="number" placeholder="reps"><input name="sets" type="number" value="3"><button class="btn primary">Log set</button></form>')+card('Hydration','<div class="water-controls"><button class="btn" data-a="water-down">−</button><strong>'+S.water+'/8 glasses</strong><button class="btn" data-a="water-up">+</button></div><div class="drops">'+Array.from({length:8},function(_,i){return '<button data-a="water" class="drop '+(i<S.water?'full':'')+'">◉</button>';}).join('')+'</div>')+'</div>');}
  function nutrition(){return layout('Nutrition','FUEL',card('Today\'s fuel',(S.meals||[]).slice(-7).reverse().map(function(x){return '<div class="row"><strong>'+esc(x.name)+'</strong><small>'+x.p+'g P · '+x.c+'g C · '+x.f+'g F</small></div>';}).join('')||'<p class="muted">Your fuel log is empty.</p>'));}
  function mind(){return layout('Mind','COGNITIVE ENGINE','<div class="stats">'+stat('FOCUS',S.study.reduce(function(a,x){return a+(+x.minutes||0);},0)+'m','this cycle')+stat('SESSIONS',S.study.length,'completed')+'</div>'+card('Focus cockpit','<button class="btn primary" data-a="pomo">Complete pomodoro</button> <button class="btn" data-a="study">Log 25 minutes</button>'));}
  function life(){return layout('Life','IDENTITY & ENVIRONMENT',card('Daily habits',(D.habits||[]).map(function(h){var m=S.habitMeta[h]||{};return '<button class="row" data-a="habit" data-h="'+esc(h)+'"><b class="check">'+(checked(h)?'✓':'')+'</b><span><strong>'+esc(h)+'</strong><small>'+(m.consecutiveDays||0)+' day streak</small></span><b>+10</b></button>';}).join(''))+card('Fasting','<button class="btn primary" data-a="fasting">Log completed fast</button>'));}
  function squad(){return layout('Squad','COMPETE WITH YOURSELF',card('Daily quests',questHtml()));} function advanced(){return layout('Advanced systems','CONTROL ROOM',card('Data & privacy','<p class="muted">Your state lives in localStorage on this device.</p><button class="btn" data-a="export">Export JSON</button> <button class="btn danger" data-a="reset">Reset system</button>')+card('Currency','<strong>'+S.creatine+' CREATINE</strong>'))}
  function render(){if(typeof document==='undefined')return;S.route=location.hash.slice(1)||S.route||'dashboard';var f={dashboard:dashboard,train:train,nutrition:nutrition,mind:mind,life:life,squad:squad,advanced:advanced}[S.route]||dashboard,x=$('#view');if(x)x.innerHTML=f();document.querySelectorAll('[data-route]').forEach(function(n){n.classList.toggle('active',n.dataset.route===S.route);});bind();}
  function form(t,f){var d=new FormData(f);if(t==='train')logWorkout({exercise:d.get('exercise'),weight:d.get('weight'),reps:d.get('reps'),sets:d.get('sets')});if(t==='meal'){var a=String(d.get('meal')||'Meal').split('|');S.meals.push({name:a[0],p:+d.get('p')||0,c:+d.get('c')||0,f:+d.get('f')||0,k:+d.get('k')||0,date:day()});save();render();}if(t==='journal'){var text=String(d.get('text')||'').trim();if(text){S.journal.push({text:text,date:day()});awardXP(10,'journal',{text:text});render();}}}
  function act(a,b){var d=b&&b.dataset?b.dataset:(b||{});if(a==='mission')awardXP(25,'mission',{skipQuest:true});else if(a==='water')waterIncrement(1);else if(a==='water-up'||a==='water-increment')waterIncrement(d.amount||1);else if(a==='water-down'||a==='water-decrement')waterDecrement(d.amount||1);else if(a==='habit')toggleHabit(d.h||d.habit);else if(a==='study')logStudy(d.min||25,d.subject);else if(a==='pomo'||a==='pomodoro-complete')completePomodoro(d.min||25,d.subject);else if(a==='fasting')completeFasting(d.hours||0);else if(a==='mood'){S.mood.push({value:d.v,date:day()});awardXP(5,'mood',{value:d.v});render();}else if(a==='quest'){quests();var q=S.quests[d.q];if(q&&q.completed)toast('Quest already complete.');}else if(a==='export'){var u=URL.createObjectURL(new Blob([JSON.stringify(S,null,2)],{type:'application/json'})),link=document.createElement('a');link.href=u;link.download='locked-in-v3.json';link.click();URL.revokeObjectURL(u);}else if(a==='reset'&&confirm('Reset all local progress?')){localStorage.removeItem(K);location.reload();}else if(a==='log')awardXP(10,'action');}
  function bind(){document.querySelectorAll('[data-a]').forEach(function(n){n.onclick=function(){act(n.dataset.a,n);};});document.querySelectorAll('[data-f]').forEach(function(n){n.onsubmit=function(e){e.preventDefault();form(n.dataset.f,n);};});var search=$('.search');if(search)search.oninput=function(){document.querySelectorAll('.ex').forEach(function(n){n.style.display=n.textContent.toLowerCase().indexOf(search.value.toLowerCase())>=0?'flex':'none';});};}
  currency();habits();resetBrokenStreaks();quests();
  window.LockedIn={state:function(){return S;},render:render,save:save,awardXP:awardXP,checkHabit:checkHabit,toggleHabit:toggleHabit,waterIncrement:waterIncrement,waterDecrement:waterDecrement,adjustWater:adjustWater,logWater:logWater,logWorkout:logWorkout,logStudy:logStudy,completePomodoro:completePomodoro,startFasting:startFasting,completeFasting:completeFasting,getStreakFeed:function(){return S.streakFeed.slice();},getDailyQuests:function(){quests();return S.quests;},addCreatine:addCreatine};
  window.addEventListener('hashchange',render);document.addEventListener('DOMContentLoaded',function(){var f=$('#onboarding-form');if(f)f.onsubmit=function(e){e.preventDefault();S.profile=Object.assign(S.profile,Object.fromEntries(new FormData(f)));S.onboarded=true;save();var o=$('#onboarding');if(o)o.close();render();};if(!S.onboarded){var o=$('#onboarding');if(o&&o.showModal)o.showModal();}render();});
})();