(function(){'use strict';
function app(){return window.app||window.LockedIn;}
function root(){return document.getElementById('app');}
function text(value){if(value===null||value===undefined){return '';}return String(value);}
function state(){var item=app();return item&&item.state?item.state:null;}
function save(){var item=app();if(item&&item.save){item.save();}else{try{localStorage.setItem('locked-in-v3-state',JSON.stringify(state()));}catch(error){}}}
function node(tag,value,kind){var item=document.createElement(tag);if(kind){item.setAttribute('class',kind);}if(value!==undefined){item.textContent=text(value);}return item;}
function card(title,body){var item=node('section',undefined,'card');item.appendChild(node('h2',title));item.appendChild(node('p',body,'muted'));return item;}
function addLink(){var nav=document.getElementsByTagName('nav').item(0);if(!nav||document.getElementById('depth-link')){return;}var item=node('button','Deep work','btn');item.setAttribute('type','button');item.setAttribute('id','depth-link');nav.appendChild(item);item.addEventListener('click',function(){var current=app();if(!current){return;}current.state.route='depth';current.render();});}
function show(){var item=root();var current=state();if(!item||!current){return;}item.replaceChildren();var hero=node('section',undefined,'hero');hero.appendChild(node('div','DEEP WORK','eyebrow'));hero.appendChild(node('h1','Build the next layer'));hero.appendChild(node('p','A quiet vault for ideas and small drills that compound.','muted'));item.appendChild(hero);var vault=current.vault||{};item.appendChild(card('Vault',text(vault.title||'No saved note yet')+' '+text(vault.detail||'Add one useful idea.')));var drill=current.drill||{};item.appendChild(card('Skill drill',text(drill.title||'Choose one skill')+' '+text(drill.detail||'Start a focused practice block.')));var form=node('form',undefined,'card');form.setAttribute('id','depth-form');form.appendChild(node('h2','Capture a note'));var field=node('input');field.setAttribute('id','depth-note');field.setAttribute('name','note');field.setAttribute('placeholder','One useful idea');form.appendChild(field);var button=node('button','Save note','btn primary');button.setAttribute('type','submit');form.appendChild(button);item.appendChild(form);form.addEventListener('submit',function(event){event.preventDefault();var input=document.getElementById('depth-note');var value=input?input.value.trim():'';if(!value){return;}current.vault={title:value,detail:'Saved locally'};save();show();});addLink();}
function install(){var current=app();if(!current||current.depthReady){return;}current.depthReady=true;var old=current.render;current.render=function(){if(current.state&&current.state.route==='depth'){show();}else{old();addLink();}};addLink();}
if(document.readyState==='loading'){document.addEventListener('DOMContentLoaded',install,{once:true});}else{install();}
}());
