(function(){
  'use strict';
  var app=window.app||window.LockedIn;
  if(!app){return;}
  var styleId='statsHubStyle';
  function addStyles(){
    if(document.getElementById(styleId)){return;}
    var style=document.createElement('style');
    style.id=styleId;
    style.textContent='.statsHub{display:grid;gap:18px}.statsIntro{margin:0 0 18px}.statsGrid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:12px}.statsMetric{min-width:0;padding:18px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(150deg,#171f2d,#0d131e)}.statsMetric small{display:block;color:var(--muted);font-size:11px;font-weight:800;letter-spacing:.1em;text-transform:uppercase}.statsMetric strong{display:block;margin:7px 0 4px;color:var(--text);font-size:27px}.statsMetric span{color:var(--muted);font-size:12px}.statsColumns{display:grid;grid-template-columns:minmax(0,1.2fr) minmax(0,.8fr);gap:18px}.statsCard{margin:0}.statsCard h2{display:flex;align-items:baseline;justify-content:space-between;gap:12px}.statsCard h2 span{color:var(--muted);font-size:11px;font-weight:500}.statsChart{display:grid;grid-template-columns:repeat(7,1fr);align-items:end;gap:8px;min-height:170px;padding:15px 4px 0;border-top:1px solid var(--line)}.statsBarGroup{display:grid;grid-template-rows:135px auto;gap:8px;text-align:center}.statsBarShell{display:flex;align-items:end;justify-content:center;height:135px}.statsBar{width:min(28px,70%);min-height:4px;border-radius:8px 8px 3px 3px;background:linear-gradient(180deg,var(--accent),var(--blue));box-shadow:0 0 18px rgba(156,255,87,.2)}.statsBarGroup span{color:var(--muted);font-size:11px}.statsBarGroup b{display:block;color:var(--text);font-size:11px}.statsRecordList{display:grid;gap:8px;margin:0;padding:0;list-style:none}.statsRecord{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 0;border-bottom:1px solid var(--line)}.statsRecord:last-child{border-bottom:0}.statsRecord strong{display:block}.statsRecord small{display:block;margin-top:3px;color:var(--muted)}.statsRecord b{color:var(--accent);white-space:nowrap}.statsEmpty{color:var(--muted)}.statsNote{margin:0;color:var(--muted);font-size:12px}.statsLegend{display:flex;flex-wrap:wrap;gap:10px 18px;margin-top:12px;color:var(--muted);font-size:12px}.statsLegend span{display:inline-flex;align-items:center;gap:6px}.statsDot{display:inline-block;width:9px;height:9px;border-radius:50%;background:var(--accent)}.statsDotBlue{background:var(--blue)}@media(max-width:900px){.statsGrid{grid-template-columns:repeat(2,minmax(0,1fr))}.statsColumns{grid-template-columns:1fr}}@media(max-width:600px){.statsGrid{grid-template-columns:1fr}.statsMetric strong{font-size:24px}}';
    document.head.appendChild(style);
  }
  function state(){return app.state();}
  function logs(){var value=state().logs;return Array.isArray(value)?value:[];}
  function text(value){return app.escape(value==null?'':String(value));}
  function number(value){var result=Number(value);return isFinite(result)?result:0;}
  function hasNumber(value){return value!==null&&value!==''&&isFinite(Number(value));}
  function kind(entry){return String(entry.type||entry.kind||'').toLowerCase();}
  function isWorkout(entry){var value=kind(entry);return value==='workout'||value==='exercise'||value==='training';}
  function isStudy(entry){return kind(entry)==='study';}
  function isWater(entry){return kind(entry)==='water';}
  function isMood(entry){return kind(entry)==='mood';}
  function dateKey(entry){var value=entry.date||entry.timestamp||'';var date=new Date(value);return isFinite(date.getTime())?date.toISOString().slice(0,10):'';}
  function reps(entry){var value=entry.reps||entry.repCount||entry.repetitions;if(hasNumber(value)){return number(value);}var detail=String(entry.detail||'');var match=detail.match(/(\d+(?:\.\d+)?)\s*reps?/i);return match?number(match[1]):0;}
  function load(entry){var value=entry.weight||entry.load||entry.kg||entry.amount;if(hasNumber(value)){return number(value);}var detail=String(entry.detail||'');var match=detail.match(/(\d+(?:\.\d+)?)\s*(?:kg|lb)/i);return match?number(match[1]):0;}
  function studyHours(entry){if(hasNumber(entry.hours)){return number(entry.hours);}if(hasNumber(entry.minutes)){return number(entry.minutes)/60;}if(hasNumber(entry.duration)){return number(entry.duration)>180?number(entry.duration)/60:number(entry.duration);}var detail=String(entry.detail||'');var match=detail.match(/(\d+(?:\.\d+)?)\s*(hours?|hrs?|minutes?|mins?)/i);if(match){return /min/i.test(match[2])?number(match[1])/60:number(match[1]);}return hasNumber(entry.value)?number(entry.value):0;}
  function water(entry){if(hasNumber(entry.glasses)){return number(entry.glasses);}if(hasNumber(entry.value)){return number(entry.value);}var detail=String(entry.detail||'');var match=detail.match(/(\d+(?:\.\d+)?)/);return match?number(match[1]):0;}
  function mood(entry){if(hasNumber(entry.mood)){return number(entry.mood);}return hasNumber(entry.value)?number(entry.value):0;}
  function totals(){var result={workouts:0,reps:0,studyHours:0,water:0,moodTotal:0,moodCount:0};logs().forEach(function(entry){if(isWorkout(entry)){result.workouts+=1;result.reps+=reps(entry);}if(isStudy(entry)){result.studyHours+=studyHours(entry);}if(isWater(entry)){result.water=Math.max(result.water,water(entry));}if(isMood(entry)){var value=mood(entry);if(value){result.moodTotal+=value;result.moodCount+=1;}}});if(!result.water){result.water=number(state().water);}result.moodAverage=result.moodCount?result.moodTotal/result.moodCount:0;return result;}
  function weekKey(day){var date=new Date(day+'T00:00:00Z');var shift=(date.getUTCDay()+6)%7;date.setUTCDate(date.getUTCDate()-shift);return date.toISOString().slice(0,10);}
  function bestWeek(){var weeks={};logs().forEach(function(entry){var day=dateKey(entry);if(!day){return;}if(!isWorkout(entry)&&!isStudy(entry)&&!isWater(entry)){return;}var key=weekKey(day);var item=weeks[key]||{count:0,days:{}};item.count+=1;item.days[day]=true;weeks[key]=item;});var best=null;Object.keys(weeks).forEach(function(key){var item=weeks[key];var active=Object.keys(item.days).length;if(!best||active>best.active||active===best.active&&item.count>best.count){best={week:key,active:active,count:item.count};}});if(!best){return 'No logged week';}return best.active+' active '+(best.active===1?'day':'days');}
  function chartDays(){var result=[];var index=6;while(index>=0){var date=new Date();date.setUTCHours(0,0,0,0);date.setUTCDate(date.getUTCDate()-index);var day=date.toISOString().slice(0,10);var count=0;logs().forEach(function(entry){if(dateKey(entry)===day){count+=1;}});result.push({day:day,count:count,label:date.toLocaleDateString(undefined,{weekday:'short',timeZone:'UTC'})});index-=1;}return result;}
  function recordMap(){var result={};logs().forEach(function(entry){if(!isWorkout(entry)){return;}var value=load(entry);var count=reps(entry);if(!value&&!count){return;}var name=entry.exercise||entry.name||entry.label||'Workout';var key=String(name).toLowerCase();var item=result[key]||{name:String(name),value:0,reps:0};if(value>item.value){item.value=value;}if(count>item.reps){item.reps=count;}result[key]=item;});return result;}
  function records(){var map=recordMap();var keys=Object.keys(map);if(!keys.length){return '<p class="statsEmpty">Log a weighted set or rep target to build personal records.</p>';}keys.sort(function(first,second){return map[second].value-map[first].value||map[second].reps-map[first].reps;});var html='<ul class="statsRecordList">';keys.slice(0,8).forEach(function(key){var item=map[key];var value=item.value?item.value+' kg':'';var count=item.reps?item.reps+' reps':'';var detail=value&&count?value+' · '+count:value||count;html+='<li class="statsRecord"><span><strong>'+text(item.name)+'</strong><small>Best logged result</small></span><b>'+text(detail)+'</b></li>';});return html+'</ul>';}
  function metric(label,value,note){return '<article class="statsMetric"><small>'+text(label)+'</small><strong>'+text(value)+'</strong><span>'+text(note)+'</span></article>';}
  function chart(){var days=chartDays();var maximum=1;days.forEach(function(item){maximum=Math.max(maximum,item.count);});var html='<div class="statsChart" role="img" aria-label="Seven day activity chart">';days.forEach(function(item){var height=Math.max(4,Math.round(item.count/maximum*100));html+='<div class="statsBarGroup"><div class="statsBarShell"><div class="statsBar" style="height:'+height+'%" aria-label="'+text(item.label)+' '+item.count+' activities"></div></div><span><b>'+item.count+'</b>'+text(item.label)+'</span></div>';});return html+'</div><div class="statsLegend"><span><i class="statsDot"></i>Stored activity</span><span><i class="statsDot statsDotBlue"></i>Last seven days</span></div>';}
  function statsView(){addStyles();var total=totals();var count=logs().length;return '<div class="statsHub"><div class="hero"><div><div class="eyebrow">CONTROL ROOM</div><h1>Stats Hub</h1><p class="muted statsIntro">A clear read on your training, study, hydration and mood. Every figure is computed from this device\'s saved logs.</p></div></div><section class="statsGrid" aria-label="Progress totals">'+metric('Workouts',total.workouts,'logged sessions')+metric('Reps',total.reps,'logged repetitions')+metric('Study hours',total.studyHours.toFixed(1),'logged focus time')+metric('Water',Math.round(total.water)+' glasses','highest logged daily total')+metric('Mood average',total.moodAverage?total.moodAverage.toFixed(1)+'/10':'No rating','from mood logs')+metric('Best week',bestWeek(),'consistency peak')+'</section><div class="statsColumns"><section class="card statsCard" aria-labelledby="statsChartTitle"><h2 id="statsChartTitle">Seven day activity <span>Today and six days back</span></h2>'+chart()+'</section><section class="card statsCard" aria-labelledby="statsRecordTitle"><h2 id="statsRecordTitle">Personal records <span>Computed from logs</span></h2>'+records()+'</section></div><section class="card statsCard" aria-labelledby="statsMethodTitle"><h2 id="statsMethodTitle">Live data note</h2><p class="statsNote" id="statsMethodTitle">Showing '+count+' stored log'+(count===1?'':'s')+'. Workout totals count workout, exercise and training entries; reps and records use the numeric fields or details attached to those entries.</p></section></div>';}
  app.registerView('stats',statsView);
  if(location.hash.slice(1)==='stats'){setTimeout(function(){app.render();},0);}
})();
